spring:
  application:
    name: notification-service
  data:
    mongodb:
      username: mf
      password: mf
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: paymentConfirmation:de.fortmeier.payment.notification.PaymentNotificationRequest,orderConfirmation:de.fortmeier.order.kafka.OrderConfirmation
  mail:
    host: localhost
    port: 1025
    username: mf
    password: mf
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8040